export default {
  products: [
    {
      _id: 1,
      name: "Slim Shirt",
      category: "Shirt",
      img: "/img/d1.jpg",
      price: 50,
      brand: "Nike",
      rating: "7.5",
      numReviews: 12,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      countInStock: 0,
    },
    {
      _id: 2,
      name: "Small Shirt",
      category: "Shirt",
      img: "/img/d1.jpg",
      price: 10,
      brand: "Adidas",
      rating: "3",
      numReviews: 10,
      countInStock: 3,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    },
    {
      _id: 3,
      name: "Big Top",
      category: "Top",
      img: "/img/d1.jpg",
      price: 80,
      brand: "Puma",
      rating: "5",
      numReviews: 5,
      countInStock: 10,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    },
    {
      _id: 4,
      name: "Slim Shirt",
      category: "Shirt",
      img: "/img/d1.jpg",
      price: 60,
      brand: "D & G",
      rating: "8",
      numReviews: 7,
      countInStock: 7,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    },
    {
      _id: 5,
      name: "Slim Shirt",
      category: "Body Hug",
      img: "/img/d1.jpg",
      price: 20,
      brand: "Nike",
      rating: "3.5",
      numReviews: 1,
      countInStock: 10,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    },
    {
      _id: 6,
      name: "Slim Shirt",
      category: "Top",
      img: "/img/d1.jpg",
      price: 30,
      brand: "Puma",
      rating: "6.5",
      numReviews: 20,
      countInStock: 5,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    },
  ],
};
